escaperoom<- function(){
  nombre<- readline(prompt = "Ingresa tu nombre :") #pedimos al usuario su nombre
  numero<- readline(prompt = "Ingresa tu número favorito :")
  a<- as.numeric(numero)
  if(numero >= 0) 
    (print(paste("BIENVENIDO A ESCAPE ROOM", nombre, "AQUÍ DEBERÁS DEMOSTRAR TUS APRENDIZAJES SOBRE MICROBIOLOGÍA,
                 LÓGICA, BIOINFORMÁTICA Y OTROS CONOCIMIENTOS PARA PODER ESCAPAR.
                 
                 Deberás tener en cuenta que todas tus respuestas tendrán que ser escritas en minúsculas y sin acentos.")))
  
  empezar <- readline(prompt = "Escribe -listo- si aceptas el desafío: ")
  if(empezar != "listo"){
    cat("")
    stop("Para iniciar el juego necesitas escribir -listo-")
  }else{
    cat("TE DESPIERTAS UN DÍA Y TE ENCUENTRAS EN UNA HABITACIÓN OSCURA, PUEDES VER SOLO UN HILO DE LUZ.
  COMO PUEDES, EMPIEZAS A BUSCAR POR TODOS LADOS INTENTANDO COMPRENDER QUÉ ESTÁ PASANDO.
  VES UNA COMPUTADORA, TE LEVANTAS, INTENTAS ENCENDER LA LUZ PERO NO FUNCIONA , TOCAS EL 
  INTERRUPTOR DE LA COMPUTADORA Y ¡OH! LA ENCIENDES, PERO TIENE UN CÓDIGO Y NO LO SABES. 
        EN LA COMPUTADORA HAY UNA PISTA : ES EL COMANDO CON QUE INICIAS UN ARCHIVO BASH")
    
    r1<- readline(prompt= "¿Cuál es el código para ingresar?:")
    if(r1== "#!/bin/bash")
      cat("MUY BIEN! LO LOGRASTE! INGRESAS A LA COMPUTADORA Y COMIENZAS A VER LOS ARCHIVOS PARA TRATAR
        DE ENCONTRAR UNA PISTA, VES UNA CARPETA LLAMADA -SALIDA- Y TE METES, PERO OH SORPRESA, ESTÁ BLOQUEDA.
        PARA DESBLOQUEARLA TE DICE: ES UN MODELO ESTOCÁSTICO, QUE MODELA DATOS TEMPORALES O SECUENCIAS,
        ES DECIR, DATOS QUE ESTÁN ORDENADOS")
    else
      cat("UFF, ESTUVO CERCA, TENDRÁS QUE ESFORZARTE MÁS SI QUIERES SALIR DE AQUÍ.
    LA COMPUTADORA SE CRASHEA Y LOGRAS INGRESAR A ELLA. COMIENZAS A VER LOS ARCHIVOS PARA TRATAR DE ENCONTRAR UNA PISTA, 
    VES UNA CARPETA LLAMADA -SALIDA- Y TE METES, PERO OH SORPRESA, ESTÁ BLOQUEDA. PARA DESBLOQUEARLA 
    TE DICE: ES UN MODELO ESTOCÁSTICO,QUE MODELA DATOS TEMPORALES O SECUENCIAS, ES DECIR, DATOS QUE ESTÁN ORDENADOS")
    
    r2 <- readline(prompt = "¿A qué se refiere esta definición?: ")
    if(r2== "modelo de markov")
      cat("EXCELENTE, SE VE QUE HAS PUESTO ATENCIÓN A TUS CLASES! INGRESAS A LA CARPETA Y SOLAMENTE VES
        UN DOCUMENTO LLAMADO -LAS MEJORES CLASES DE ROBERTO- Y OTRO LLAMADO -CHISMES DE MICRO-. POR 
        CHISMOSO TE METES A ESE Y RESULTA SER UNA TRAMPA, EN EL SOLO ENCUENTRAS 2 PREGUNTAS DE CULTURA 
        GENERAL DE LA MICROBIOLOGÍA")
    else
      cat("BUEN INTENTO, IMAGINO QUE TE GUSTA SER PARTE DEL JUEGO. SIGAMOS POR OTRO RUMBO.
        NO PUDISTE ENTRAR A LA CARPETA, PERO LA LUZ DE MONITOR ENCENDIDO TE PERMITE TENER UNA VISIÓN
        UN POCO MÁS CLARA. VOLTEAS A TU IZQUIERDA Y VES UNA CARTA, LA TOMAS Y EN ELLA VES 2 PREGUNTAS
        DE CULTURA GENERAL DE LA MICROBIOLOGÍA: ")
    
    r3 <- readline(prompt = "¿Cómo se le llama al desequilibrio de la microbiota?, ¿Cómo se le llama a la expresión cuantitativa de la patogenicidad?: ")
    if(r3== "disbiosis, virulencia")
      cat("SI QUE HAS ESTADO ESTUDIANDO, AL CONTESTAR LAS PREGUNTAS TE REGRESA A LAS 2 CARPETAS, ENTRAS AHORA 
        LAS MEJORES CLASES DE ROBERTO Y TE ENCUENTRAS CON UNA ENCRIPTACIÓN PARA PODER INGRESAR, DICE: PARA 
        PODER INGRESAR, LA PALABRA DEBES DESCIFRAR: -.....---..-...-.---.-.--.--..-.-..-")
    
    else 
      cat ("NO LOGRAS SALIR DE LA CARPETA, ASI QUE DECIDES REINICIAR LA COMPUTADORA, REGRESAS Y ABRES LA CARPETA
        LAS MEJORES CLASES DE ROBERTO Y TE ENCUENTRAS CON UNA ENCRIPTACIÓN PARA PODER INGRESAR, DICE: PARA 
        PODER INGRESAR LA PALABRA DEBES DESCIFRAR: -.....---..-...-.---.-.--.--..-.-..-")
    
    r4<- readline(prompt= "¿Cuál es la palabra para entrar?:")
    if(r4=="bioinformatica")
      cat("EXCELENTE! HAS INGRESADO A LA CARPETA, DONDE SE ENCUENTRA LA FOTO DE UNA CAJA FUERTE Y DOS ECUACIONES:
    x^2−4x+3=0 Y x^2+3x−10=0, EN LA CAJA SE OBSERVA QUE SE PIDEN 4 NÚMEROS PARA ABRIRLA, ASI QUE ASUMES QUE 
        LAS SOLUCIONES DE LAS ECUACIONES TE DARÁN LA CLAVE,RESUELVES LAS ECUACIONES Y TE DIRIGES A BUSCAR ESA CAJA
        FUERTE CON LA POCA LUZ QUE HAY EN LA HABITACIÓN, LA VES DEBAJO DE UNA MESA Y TE ACERCAS")
    else
      cat ("¡VAMOS, PUEDES HACERLO MEJOR! RECUERDAS TUS HABILIDADES PARA HACKEAR Y ENTRAS EN LA CARPETA, DONDE SE ENCUENTRA 
    LA FOTO DE UNA CAJA FUERTE Y DOS ECUACIONES:x^2−4x+3=0 Y x^2+3x−10=0, EN LA CAJA SE OBSERVA QUE SE PIDEN 4 NÚMEROS 
    PARA ABRIRLA, ASI QUE ASUMES QUE LAS SOLUCIONES DE LAS ECUACIONES TE DARÁN LA CLAVE, RESUELVES LAS ECUACIONES Y 
    TE DIRIGES A BUSCAR ESA CAJA FUERTE CON LA POCA LUZ QUE HAY EN LA HABITACIÓN, LA VES DEBAJO DE UNA MESA Y TE ACERCAS")
    
    r5<- readline(prompt = "¿Cuál es el código para abrir la caja?:
  (si tu solución es negativa no incluyas el signo. Escribe los números sin separación iniciando con la solución obtenida
                utilizando el signo positivo)")
    if(r5==3125)
      cat("¡VAS POR BUEN CAMINO!, ABRES LA CAJA FUERTE Y ENCUENTRAS UN CELULAR, PARA INGRESAR TE PIDE CONTESTAR VERDADERO O FALSO:")
    
    else 
      cat("¡TÚ PUEDES, NO TE DESANIMES! NO PUEDES ABRIR LA CAJA FUERTE, TE SIENTES TRISTE Y DESANIMADO, TE ACUESTAS EN EL SUELO 
        Y LOGRAS VER DEBAJO DE LA CAMA UN OBJETO, TE ACERCAS A EL Y VES QUE ES UN CELULAR, PERO PARA INGRESAR TE PIDE
        CONTESTAR VERDADERO O FALSO:")
    
    r6 <- readline(prompt = "La dimensión de una matriz se puede obtener usando la función dimensions(): ")
    if(r6=="falso")
      cat("SE NOTA QUE ERES UNA PERSONA OBSERVADORA. EN EL CELULAR VES UNA NOTA QUE DICE: PARA LA SALIDA ENCONTRAR, EL NÚMERO SECRETO
    DEBES ADIVINAR.- Y LO UNICO QUE TE DAN SON 3 NOMBRES: JERRY, BET Y SUMMER ")
    
    else
      cat("UNA CONFUSIÓN QUE A TODOS NOS PASA. NO PUDISTE INGRESAR EN EL CELULAR, PERO ABRES LA TAPA DE ATRÁS Y ENCUENTRAS 
        UN PAPEL QUE DICE: -PARA LA SALIDA ENCONTRAR, EL NÚMERO SECRETO DEBES ADIVINAR.- Y LO UNICO QUE TE DAN SON 3 NOMBRES: 
        JERRY, BET Y SUMMER")
    
    r7 <- readline(prompt = "¿Cúal es el número secreto?: ")
    if(r7== 14)
      cat("GENIAL, CADA VEZ TE ACERCAS MÁS A LA SALIDA, PERO NO SERÁ TAN FÁCIL, AUNQUE HAS LOGRADO SUPERAR ESTA PRUEBA
    SIN EQUIVOCARTE, ¡NO TE CONFIES!
    
    DURANTE TU RECORRIDO POR LA HABITACIÓN ENCUENTRAS UNA HOJA QUE DICE: -MIRA DE CERCA EN EL ESCRITORIO-, AL MIRAR 
    TE ENCUENTRAS DEBAJO DEL ESCRITORIO OTRA HOJA CON EL SIGUIENTE LINK (https://unidaddememoria.blogspot.com/2015/03/encuentra-la-logica-y-resuelve-7-3-2015.html)
        DECIDES ABRIRLO EN LA COMPUTADORA Y PARECE UN ACERTIJO")
    
    else
      cat ("SABÍA QUE NO PODRÍAS Y TE EQUIVOCARÍAS. PERO PARA TU BUENA SUERTE AL DARLE VUELTA AL PAPEL TE ENCUENTRAS
    OTRO ESCRITO QUE DICE: -ES TU SEGUNDA OPORTUNIDAD, PON ATENCIÓN AL ACERTIJO MENCIONADO O QUEDARAS ATRAPADO-.Y TE 
    ENCUENTRAS CON EL SIGUIENTE LINK (https://unidaddememoria.blogspot.com/2015/03/encuentra-la-logica-y-resuelve-7-3-2015.html)
        DECIDES ABRIRLO EN LA COMPUTADORA Y PARECE UN ACERTIJO")
    
    r9<- readline (prompt= "¿Cuál es la solución del acertijo?: " )
    if(r9==60840)
      cat ("WOW, ME SORPRENDE TU CAPACIDAD DE OBSERVACIÓN Y LÓGICA. CADA VES ESTÁS MÁS CERCA DE ESCAPAR.
   
    RECORRES NUEVAMENTE LA HABITACIÓN GIRANDO EL MONITOR PARA TENER UN POCO MÁS DE LUZ Y TE ENCUENTRAS CON UNA FOTO DE LA
    PUERTA DE SALIDA Y UNA LLAVE, TOMAS LA LLAVE Y LA LLEVAS A LA PUERTA, INTENTAS ABRIRLA PERO NO FUNCIONA, 
    OBSERVAS AL REDEDOR Y VOLTEAS EL ESCRITORIO, ENCUENTRAS UN CAJÓN QUE NO HABÍAS VISTO Y USAS LA LLAVE EN EL,
    LO ABRES Y ENCUENTRAS UNA NOTA QUE DICE: SON MÉTODOS DE CONSTRUCCIÓN DE ÁRBOLES BASADOS EN DISTANCIA")
    
    else
      cat ("NO TE RINDAS, ¡HAS LLEGADO MUY LEJOS! 
    RECORRES NUEVAMENTE LA HABITACIÓN GIRANDO EL MONITOR PARA TENER UN POCO MÁS DE LUZ Y TE ENCUENTRAS CON UNA FOTO DE LA
    PUERTA DE SALIDA Y UNA LLAVE, TOMAS LA LLAVE Y LA LLEVAS A LA PUERTA, INTENTAS ABRIRLA PERO NO FUNCIONA, 
    OBSERVAS AL REDEDOR Y VOLTEAS EL ESCRITORIO, ENCUENTRAS UN CAJÓN QUE NO HABÍAS VISTO Y USAS LA LLAVE EN EL,
    LO ABRES Y ENCUENTRAS UNA NOTA QUE DICE: ES UN MÉTODO DE CONSTRUCCIÓN (DE 5 LETRAS) DE ÁRBOLES BASADOS EN DISTANCIA")
    
    r10<- readline (prompt = "¿De qué método estamos hablando?: ")
    if (r10== "upgma")
      cat("ERES INCREÍBLE. ABAJO DE ESA NOTA EN LETRAS PEQUEÑAS VES QUE DICE: *LAS INICIALES DEBERÁS OBSERVAR, SI LA LLAVE
          QUIERES ENCONTRAR, DIVIDE 2-1-2 Y SABRÁS A DÓNDE MIRAR, EN QUÉ COLOR CENTRARTE Y Y QUÉ MATERIA APLICAR* 
          
          DESPUÉS DE ARDUA OBSERVACIÓN DESCUBRES QUE ES -UP-GREEN-MATH, ASÍ QUE MIRAS ARRIBA, VES UNA PINTURA VERDE Y EN ELLA
          AL PADRE DE LA BIOIFORMÁTICA, (QUE ALGUNA VES TE ENSEÑÓ SOBRE BIOSTRINGS), ASÍ QUE AGARRAS LA PINTURA, PERO NO VES 
          NADA, LA VOLTEAS Y TE ENCUENTRAS UNA PREGUNTA QUE TIENES QUE CONTESTAR CON VERDADERO O FALSO: ")
    
    else
      cat("NOOO, ERA UPGMA, PERO NO TE PREOCUPES, AHORA LO SABES! ABAJO DE ESA NOTA EN LETRAS PEQUEÑAS VES QUE DICE: 
    *LAS INICIALES DEBERÁS OBSERVAR, SI LA LLAVE QUIERES ENCONTRAR, DIVIDE 2-1-2 Y SABRÁS A DÓNDE MIRAR, EN QUÉ COLOR 
    CENTRARTE Y Y QUÉ MATERIA APLICAR* 
    
    DESPUÉS DE ARDUA OBSERVACIÓN DESCUBRES QUE ES -UP-GREEN-MATH, ASÍ QUE MIRAS ARRIBA, VES UNA PINTURA VERDE Y EN ELLA
    AL PADRE DE LA BIOIFORMÁTICA (ROBERTO), QUE ALGUNA VES TE ENSEÑÓ SOBRE BIOSTRINGS, ASÍ QUE AGARRAS LA PINTURA, PERO NO VES 
        NADA, LA VOLTEAS Y TE ENCUENTRAS UNA PREGUNTA QUE TIENES QUE CONTESTAR CON VERDADERO O FALSO: ")
    
    r11<- readline (prompt = "¿La libreria de Biostrings es unica y exclusivamente para manipular cadenas de ARN?: ")  
    if(r11== "falso")
      cat ("VAYA, SÍ QUE ERES INTELIGENTE. LOGRAS NOTAR QUE EL CUADRO ESTÁ FORRADO CON UN PAPEL EN LA PARTE TRASERA. QUITAS ESE
         FORRO Y ENCUENTRAS OTRA LLAVE. ESPERANSADO QUE SEA LA DE LA PUERTA VAS A ELLA Y VES: -ESTÁ ES TU ÚLTIMA PRUEBA,
         SI CONTESTA ESTA PREGUNTA BIEN SERÁS LIBRE: ")
    
    else
      cat ("FALLASTE VILMENTE. TAL VEZ NO PONGAS ATENCIÓN A TUS CLASES, PERO ERES OBSERVADOR. TE DAS CUENTA QUE EL CUADRO ESTÁ
    FORRADO CON UN PAPEL EN LA PARTE TRASERA. QUITAS ESE FORRO Y ENCUENTRAS OTRA LLAVE. ESPERANSADO QUE SEA LA DE LA PUERTA
    VAS A ELLA Y VES: -ESTÁ ES TU ÚLTIMA PRUEBA, SI CONTESTA ESTA PREGUNTA BIEN SERÁS LIBRE:  ")
    
    r12 <- readline (prompt = "Considerando la matriz de transiciones de un modelo de Markov. ¿Cuál es la probabilidad de tener 
                   la siguiente secuencia: rainy, sunny, snowy, rainy?: ")
    if(r12== "P(sunny|rainy)*P(snowy|sunny)*P(rainy|snowy)")
      print(paste("¡¡¡LO LOGRASTE, ERES LIBRE!!! FELICIDADES", nombre,
                  for(i in 1:10){print("we are the champion ")
                  })) 
    
    else
      print(paste("NO PUDISTE ESCAPAR, PERO NO TE PREOCUPES, ¡SIEMPRE PUEDES VOLVER A INTENTARLO! GRACIAS POR JUGAR", nombre,
                  for(i in 1:10){print("error")
                  }))
  }
}

escaperoom()